version: '3'

services:
  clarin-tei:
    build:
      # need to include files from parent dir (see Dockerfile)
      context: ../
      dockerfile: docker/clarin-tei/Dockerfile
    restart: unless-stopped
    volumes:
      - ${CLARIN_TEI_FILES_DIR}:/etc/clarin-tei/files
    ports:
      - "6789:6789"
