version: '3'

services:

  nginx-reverse-proxy:
    build:
      context: nginx-reverse-proxy
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - glossematics
    environment:
      - CERTBOT_EMAIL=simongray@hum.ku.dk
      - STAGING=0
      - DHPARAM_SIZE
      - RSA_KEY_SIZE
      - RENEWAL_INTERVAL
    ports:
      - 80:80
      - 443:443
      - 8080
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  glossematics:
    build:
      # need to include files from parent dir (see Dockerfile)
      context: ../
      dockerfile: docker/glossematics/Dockerfile
    restart: unless-stopped
    volumes:
      - ${GLOSSEMATICS_CONF}:/etc/glossematics/conf.edn
      - ${GLOSSEMATICS_IDP_CERTIFICATE}:/etc/glossematics/idp-certificate.pem
      - ${GLOSSEMATICS_SAML_KEYSTORE}:/etc/glossematics/saml-keystore.jks
      - ${GLOSSEMATICS_FILES_DIR}:/etc/glossematics/files
      - ${GLOSSEMATICS_DB_DIR}:/etc/glossematics/db
    ports:
      - 8080:8080
